download.js
package.json

Vagrant don't allow to create hard link on shared folders. This pull-request try to create a duplicate of the original file if underlying filesystem don't support hard links, like FAT does.

Allow create files for hard links

---

package.json

No relevant breaking changes for `prebuild-install`. Just to receive future updates.

Bump node-abi@2.0.0

---

download.js
package.json

This ensures that we can create multiple directories at once
https://github.com/electron-userland/electron-builder/issues/1415 is caused by this since it needs to create `.electron-gyp/.npm`.

fix: use mkdirp for creating directories

---

test/util-test.js
util.js

This should fix #32. I left the previous implementation as a fallback, because I don't know if all npm versions set the `npm_config_cache` env variable.

make use of npm_config_cache

---

package.json

Otherwise "Could not detect abi for version 1.8.0 and runtime electron.  Updating "node-abi" might help solve this issue if it is a new release of electron"
Please publish new version after merge if possible.

Update node-abi to 2.1.1 for Electron 1.8.0 support

---

.travis.yml
README.md

Fixes broken travis badge and adds node 9 to travis. (I also enabled prebuild org on travis).

tweak readme + update node versions + standard

---

download.js
test/download-test.js

The noop logger doesn't have an http method. It also doesn't have a silly method, and this project doesn't do `log.silly()` anywhere, but I figured I'd add it too just to make sure all the `npmlog` methods have equivalents here.

Fix download API crash when no logger specified

---

package.json
rc.js
test/rc-test.js

Hello, this PR is the "partner" commit of https://github.com/prebuild/prebuild/pull/180 to detect the libc family at install time.
The `detect-libc` dependency is already used by [node-pre-gyp](https://github.com/mapbox/node-pre-gyp/blob/f21830e2946d140b8b424b0f3acf4fb81eaa01e7/package.json#L31) for the same purpose.

Add detection for non-glibc libc on Linux

---

package.json

Follow-up from https://github.com/prebuild/prebuild/pull/203 and https://github.com/lgeiger/node-abi/pull/34#issuecomment-360634948.

Bumping node-abi version for node-webkit runtime support.

---

bin.js
package.json
test/util-test.js
util.js

Like Yarn, [pnpm](https://github.com/pnpm/pnpm) does not add a `_from` field to the `package.json` files of the installed dependencies. So pnpm needs the same workaround as Yarn

fix: download prebuilt binaries when installing with pnpm

---

util.js

This implements Option 2 from https://github.com/prebuild/prebuild-install/issues/77.
The test file's name changes from 
```
https-github.com-ralphtheninja-a-native-module-releases-download-v1.0.0-a-native-module-v1.0.0-node-v59-win32-x64.tar.gz
```
to
```
36772a-a-native-module-v1.0.0-node-v59-win32-x64.tar.gz
```
This is mostly for continuing the discussion from #77 -- let me know if you'd rather have what I outlined in Option 1 or something else entirely.
It might also make sense to actually verify that the filename is shorter than 140 chars and truncate part of it if that's the case.

Shortened filename in cache

---

download.js
test/asset-test.js
test/download-test.js
util.js

See discussion in https://github.com/prebuild/prebuild-install/pull/80

remove .nolocal (remnant from prebuild)

---

download.js

Encountered an issue when trying to download prebuild binary for a certain architecture, while doing it using node with a different one (i.e. npm install --arch=ia32 but node is x64).
If platforms are different, there's no point in requiring the downloaded module, as it will throw anyway

Skipping require-test after download if process arch is not same as downloaded

---

package.json

Hello, this change involves a major version increment of `expand-template` but I think the bump is only due to its Node 6 minimum that now matches this module. All the existing tests continue to pass.
The main benefit of upgrading is to pick up the correct licensing details from the latest version of this module.

Bump expand-template to correct licensing details

---

bin.js

I'm a maintainer on [`keytar`](https://github.com/atom/node-keytar) and had to deal with the Electron 3/4 transition which had a known ABI issue that impacted native modules, discussed here https://github.com/lgeiger/node-abi/issues/54. We were able to workaround it by blocking clients from trying to download these packages, and I thought I'd upstream this fix to see if you were interested in making this available more broadly for anyone else who happens to stumble into it.
In a nutshell, this setup of `prebuild` packages should not be used if they were created:
- `electron` runtime
- a target between `4.0.0` and `4.0.3` (inclusive)
- ABI 64 (Node 4 now uses 69 for it's ABI)
The patch to `node-abi` to support this new ABI is now available, so that future prebuild installs will avoid all …

add workaround to block preinstall for known issue with Electron 4.0.x

---

rc.js
test/rc-test.js

Add support for the build_from_source npm config

---

rc.js
test/rc-test.js

This change adds support to detect the `yarn --verbose ...` flag and pass it through to `rc`, thus enabling verbose logging when requested.
This is required for `yarn` as it sets `npm_config_argv` but does not set `npm_config_loglevel` - see https://github.com/yarnpkg/yarn/issues/2472

Ensure --verbose flag is passed through to rc options

---

package.json

I had a project that received a GitHub alert based on a [minimist prototype pollution vulnerability reported to NPM](https://github.com/angular/angular/issues/36104), instructing to update to 1.2.3 ([more details here](https://snyk.io/vuln/SNYK-JS-MINIMIST-559764)). One of the dependencies using 1.2.0 was prebuild-install (depended on via serialport). As with https://github.com/angular/angular/issues/36104, I was able to fix it with `"resolutions": { "minimist": "^1.2.3" }`.
While this is a minor upgrade, I cannot easily verify the result because 30/33 tape tests fail on my system both with and without 1.2.3. Happy to go through those steps if other configuration is required.

Updates minimist to 1.2.3 to resolve dependency vulnerability

---

rc.js

https://unix.stackexchange.com/questions/212894/whats-the-right-format-for-the-http-proxy-environment-variable-caps-or-no-ca

http_proxy(or https_proxy) might be lower case

---

.travis.yml
bin.js
log.js
package.json
rc.js
test/rc-test.js
test/skip-test.js
test/util/clean-env.js
util.js

Support npm 7

---

README.md
bin.js
rc.js
test/rc-test.js

In favor of `--build-from-source` which is a common option among build tools (`node-gyp-build`, `node-pre-gyp`). The `--compile` option was an alias and `--prebuild` is the default behavior anyway.

Breaking: remove --compile and --prebuild options

---

util.js

This check is superfluous. The default is set in `rc.js`. If we want to be type safe for `expandTemplate()` we can add a type check if we want to but I think it is not necessary.
fixes #141

fixes empty --tag-prefix

---

README.md
download.js
rc.js
test/download-test.js
test/util-test.js
util.js

See #136 for discussion
When an arch/platform/version does not have a published prebuild, we currently have two options:
1. Host an HTTP server with the proper directory structure to serve the missing prebuilds, *and* set `node_config_${package}_binary_host` in the build environment
2. Wait for CI flow to build the native modules
This PR enables users to provide prebuilds via the host's filesystem.
- Reinstates code removed by a06925378d38ca821bfa93aa4c1fdedc253b2420
- Adds `--local-prebuilds` flag to specify prebuild dir
- Adds `npm_config_${pkg.name}_local_prebuilds` env var to specify prebuild dir
- Adds tests for local prebuilds
I mostly just re-added previously existing code. I also added:
- var + env config for the otherwise hard-coded `prebuilds` dir
- tests

Local prebuilds

---

bin.js
package.json

The issue comes from this changes 4 years ago which fixed the issue that sources were always compiling when used in yarn: https://github.com/prebuild/prebuild-install/commit/e9065dd0e1c090fd4966496091fc1f27b074fadd
This fix seems irrelevant by now, when one looks at the code paths. It also blocks the usage of the force and buildFromSource options. It seems safe to simply remove the check altogether. I have verified that doing so makes `prebuild-install` correctly download or build from source when explicitly told so, using yarn.
Co-authored-by: Benjamin Pasero <benjpas@microsoft.com>
Fixes: https://github.com/prebuild/prebuild-install/issues/139

Fix: force, buildFromSource cli opts are ignored in yarn

---

test/util-test.js
util.js

Fixes #147 and adds support for scoped packages with URL-safe names.

fix: Support URL-safe strings in scoped packages

---

README.md

The thought of npm-deprecating `prebuild(-install)` crossed my mind; this is a less aggressive form of that.
The text here is a combination of comments by @mafintosh, @bcomnes (https://github.com/prebuild/prebuildify/pull/33) and @pimterry (https://github.com/node-ffi-napi/node-ffi-napi/pull/63#issuecomment-604471828).

Point users towards prebuildify

---

rc.js
test/rc-test.js

I went ahead and implemented the suggestion by @vweevers. This will make `rc.path` an absolute path.
This fixes #157.

Make 'rc.path' absolute

---

download.js
test/asset-test.js

As mentioned in issue #121 Github will deprecate auth via query param, so we move this to http header.
Read more about Github's decision to deprecate [here](https://developer.github.com/changes/2020-02-14-deprecating-oauth-app-endpoint/).

Move auth token to header instead of query param

---

.github/workflows/test.yml
package.json

https://github.com/electron/node-abi/issues/113 was fixed in 3.3.0
and is affecting electron 14+
With the current node-abi prebuild-install will download ABI 89 for
electron 14 and 15 and then modules will fail to load as electron 14
has ABI 97 and electon 15 has ABI 98 in reality.

deps: update node-abi so that electron 14+ get correct node-abi

---

package.json
rc.js

Hi, the latest [detect-libc](https://www.npmjs.com/package/detect-libc) has been modernised to use the non-blocking Node.js Report API where available (Node.js >= 12), falling back to use an efficient single child process with older versions.
It's a major version bump for detect-lib as it drops support for versions of Node.js < 8. Given prebuild-install already requires >= 10 this PR should OK to include in a patch release.
There's an extensive integration test suite, e.g. https://github.com/lovell/detect-libc/actions/runs/1717414863
Should anyone be interested in the background to this, please see https://github.com/lovell/detect-libc/issues/14

Upgrade to version 2 of detect-libc

---

README.md
rc.js
test/rc-test.js
util.js

Option `--libc` can be used to download musl packages on glibc and other platforms, but cannot be used to download glibc packages on musl platforms. In other words, I can pass `--libc=musl` or `--platform=linuxmusl` on any platform to install prebuild linuxmusl packages for cross-platform target.
On the other hand, if I pass `--platform=linux` on Alpine Linux, `linuxmusl` packages are still downloaded. If I pass `--libc=glibc`, it tries to download `linuxglibc` packages that don't exist. This effectively prevents building cross-platform packages for glibc Linux targets on Alpine Linux.
Additionally, this PR allows passing `--libc` option to npm in and it will be used when installing. This allows projects depending on prebuild-install to install desired libc variant.
It could be considered …

Allow setting libc to glibc on non-glibc platform

---

log.js
test/skip-test.js

Replaces the temporary logfile workaround with the use of the `foreground-scripts` setting, available in npm v7+.
https://docs.npmjs.com/cli/v8/using-npm/config#foreground-scripts
(This should hopefully make removing `npmlog` a tiny bit easier.)

Tests: ensure 'npm install' script output can be captured

---

log.js
package.json

This is a possible approach to address https://github.com/prebuild/prebuild-install/issues/163
The `npmlog` dependency always writes to `stderr` so the use of `console.error()` is consistent with the previous behaviour.
https://github.com/npm/npmlog/blob/7aefa36320a4265f2825f34db29f129f5927f41b/lib/log.js#L12
All existing log message formats and levels remain as before, which takes advantage of existing tests that cover these.
We could remove the concept of levels entirely, but that would have a slightly wider impact and I've not attempted it here.
Closes #163, closes #116.

Replace use of npmlog dependency with console.error

---

util.js

This allows prebuild-install to be used on fips systems

Use sha1, instead of md5

---

package.json

Fixes https://github.com/prebuild/prebuild-install/issues/203.
I don't have a good mechanism to test the changes inside prebuild-install without publishing releases of these packages, but I can test the new version of napi-build-utils in our package and confirm that it detects the correct version of napi.
I tested this in the @mongodb-js/zstd package by installing napi-build-utils@2.0.0 and confirming that it now detects an napi version of 4:
before fix:
```shell
> require('napi-build-utils/package.json').version
'1.0.2'
> require('./package.json').binary
{ napi_versions: [ 4 ] }
> require('napi-build-utils').getBestNapiBuildVersion()
undefined
```
after fix:
```shell
> require('./package.json').binary
{ napi_versions: [ 4 ] }
> require('napi-build-utils/package.json').version
'2.0.0'
> …
```

Bump napi-build-utils from 1 to 2
