download.js
package.json

Ported from mafintosh/prebuild#111

Removed check for invalid archive on download

---

README.md

Did this on mobile.  Hope this works :)

readme: remove dupe argument

---

package.json

Again from mobile,  cause I'm sick in bed. Hope without typos :)

Add mathiask88 as contributor

---

bin.js

bail out on download for git and dev installations

---

rc.js

Backported from https://github.com/mafintosh/prebuild/pull/156

Get target architecture from npm config environment variables

---

package.json

vulnerability details:
https://snyk.io/vuln/npm:tunnel-agent:20170305
Closed by upgrading to latest version of tunnel-agent

Closes vulnerabnility in tunnel-agent

---

.gitignore
.travis.yml

No reason to release a new version once merged.

add node 8 to travis

---

README.md
rc.js
test/rc-test.js

Fix #43 using solution proposed in https://github.com/prebuild/prebuild-install/issues/43#issuecomment-333261243
cc @ralphtheninja

Pass through download argument from npm

---

README.md
test/util-test.js
util.js

Hi!
I've added possibility for the end user to upload binaries to custom location and serve them from there. This is extremely useful in certain cases, e.g. when github dl/ul is blocked (like at my workplace).
Kind regards,
Dennis

Implement possibility of download url override using environment variables

---

bin.js
help.txt
rc.js

Add --force flag to force the use of prebuilt binaries when available

---

download.js

https://github.com/prebuild/prebuild-install/issues/51
@ralphtheninja Something like this?

add log entry if proxies are being used

---

bin.js
download.js
package.json
test/rc-test.js
test/util-test.js

replace xtend with object.assign(...)

---

README.md
appveyor.yml

adds appveyor config

---

README.md
asset.js
help.txt
rc.js
test/asset-test.js
test/rc-test.js

Works https://github.com/prebuild/prebuild/issues/229

Add --tag-prefix option for github releases

---

test/util-test.js
util.js

To tackle https://github.com/prebuild/prebuild-install/issues/96

Replace '-' with '_' in pkg name when checking env

---

download.js
package.json

Closes https://github.com/prebuild/prebuild-install/issues/126

Replace mkdirp with mkdirp-classic

---

CHANGELOG.md
CONTRIBUTING.md
README.md
package.json

Add changelog

---

README.md
help.txt

#125 document cross platform options

---

asset.js
download.js
package.json
proxy.js
util.js

Inline no longer maintained `noop-logger`

---

util.js

Fix for https://github.com/prebuild/prebuild-install/issues/152

Remove _ prefix as they aren't allowed by npm config
